# syntax=docker/dockerfile:1

FROM golang:latest AS build

RUN mkdir /app
WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY *.go ./

RUN go build -o /wapp


# Next container
FROM alpine:latest

WORKDIR /

COPY --from=build /wapp /wapp

EXPOSE 8080

ENTRYPOINT ["/wapp"]
